### PR TITLE
Fix table layout

### LINKED ISSUE #8: The tables behave weird until they are selected
To reproduce:
1. Load a database
2. Open the Items Table Overview

### PR DESCRIPTION
**Pull request by david-buderus**
Fix #8

### CODE REVIEW

File: src/main/java/ui/part/WrappingTableCell.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        Text text = new Text(item);
+        text.setStyle(" -fx-text-wrap: true;");
+
+        calculateSize(text);
+        this.widthProperty().addListener((ob, o, n) -> calculateSize(text));
+
+        this.setGraphic(text);
+    }
+
+    private void calculateSize(Text text) {
```
Comment (bastihav) [inline src/main/java/ui/part/WrappingTableCell.java]: calculateSize should be called something else..
you update the width of the text and the height of the cell..
so synchronizeCellAndTextSizes()  ? idk, something like that maybe

File: src/main/java/ui/part/WrappingTableCell.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+        double width = this.getTableColumn().getWidth() - 10;
```
Comment (bastihav) [inline src/main/java/ui/part/WrappingTableCell.java]: why -10? this should be documented.. is it because of the scroll bar? If so, try to get the width of the sroll bar instead of using a magic constant

File: src/main/java/ui/part/WrappingTableCell.java [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+        text.setWrappingWidth(width);
+        this.setPrefHeight(text.getLayoutBounds().getHeight() + 10);
```
Comment (bastihav) [inline src/main/java/ui/part/WrappingTableCell.java]: again, why +10?

File: src/main/java/ui/part/WrappingTableCell.java (hunk 2 above)
Comment (david-buderus) [reply src/main/java/ui/part/WrappingTableCell.java]: This is only used so the text wrapping is not at the border of the column.
Looks better

File: src/main/java/ui/part/WrappingTableCell.java (hunk 3 above)
Comment (david-buderus) [reply src/main/java/ui/part/WrappingTableCell.java]: It is only used so the text has space under it and is not at the border of the row

**Review by bastihav — APPROVED** [review]
